# This file is an attempt at matching the encoding used by the bootleg Russian
# translation of GTA: Vice City by "Tycoon", the most commonly used translation
# back in the 2000s. A feature of this translation is that it exclusively uses
# lowercase letters in Russian text. Some of the letters pull double duty as
# both Latin and Cyrillic characters -- these are given their Cyrillic mappings
# in this table.
[decode_table]
97 = 'а' # Latin a
151 = 'б'
152 = 'в'
153 = 'г'
175 = 'д'
101 = 'е' # Latin e
154 = 'ж'
171 = 'з'
156 = 'и'
174 = 'й'
107 = 'к' # Latin k
157 = 'л'
109 = 'м' # Latin m
104 = 'н' # Latin h
111 = 'о' # Latin o
158 = 'п'
112 = 'р' # Latin p
99 = 'с' # Latin c
116 = 'т' # Latin t
121 = 'у' # Latin y
159 = 'ф'
120 = 'х' # Latin x
160 = 'ц'
165 = 'ч'
166 = 'ш'
167 = 'щ'
# There is no 'ъ' in the translated game's fonts.
169 = 'ы'
168 = 'ь'
170 = 'э'
155 = 'ю'
172 = 'я'
